name       : haskell-pantry
version    : 0.2.0.0
release    : 1
source     :
    - https://hackage.haskell.org/package/pantry-0.2.0.0/pantry-0.2.0.0.tar.gz : 8cd8b4192c0a1e37666852306d588a6db03ea03363572e0e54e0e8a9aa19e2e2
license    : BSD-3-Clause
component  : programming.haskell
summary    : Content addressable Haskell package management
description: |
    Content addressable Haskell package management, providing for secure, reproducible acquisition of Haskell package contents and metadata.
builddeps  :
    - haskell-cabal-install
    - haskell-filelock-devel
    - haskell-generic-deriving-devel
    - haskell-hackage-security-devel
    - haskell-hpack-devel
    - haskell-http-download-devel
    - haskell-persistent-sqlite-devel
    - haskell-persistent-template-devel
    - haskell-rio-orphans-devel
    - haskell-tar-conduit-devel
    - haskell-th-utilities-devel
    - haskell-zip-archive-devel
rundeps    :
    - devel:
        - haskell-filelock-devel
        - haskell-generic-deriving-devel
        - haskell-hackage-security-devel
        - haskell-hpack-devel
        - haskell-http-download-devel
        - haskell-persistent-sqlite-devel
        - haskell-persistent-template-devel
        - haskell-rio-orphans-devel
        - haskell-tar-conduit-devel
        - haskell-th-utilities-devel
        - haskell-zip-archive-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
